# Generated by Django 5.2.16 on 2026-07-10 23:25

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='America/Los_Angeles', help_text='IANA timezone key, e.g. America/Los_Angeles', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=100)),
                ('rooms_tab', models.CharField(blank=True, default='Rooms', max_length=100)),
                ('equipment_tab', models.CharField(blank=True, default='Equipment', max_length=100)),
                ('schedule_tab', models.CharField(blank=True, default='Events', max_length=100)),
                ('staff_tab', models.CharField(blank=True, default='Staff Shifts', max_length=100)),
                ('checklist_tab', models.CharField(blank=True, default='Room Checklist', help_text='Blank to disable checklist sync for this event.', max_length=100)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.event')),
            ],
            options={
                'ordering': ['category', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('layout_image', models.ImageField(blank=True, upload_to=events.models.room_image_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.event')),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('equipment_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_name', models.CharField(max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='events.room')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['equipment_type', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.room')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, max_length=100)),
                ('room_name', models.CharField(blank=True, max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('has_av', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='events.event')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='events.room')),
            ],
            options={
                'ordering': ['starts_at', 'room_name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='events.event')),
            ],
            options={
                'ordering': ['starts_at', 'staff_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('event', 'building', 'room_number'), name='uniq_room_per_event'),
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['event', 'starts_at'], name='events_sche_event_i_950c79_idx'),
        ),
        migrations.AddIndex(
            model_name='staffshift',
            index=models.Index(fields=['event', 'starts_at'], name='events_staf_event_i_8eefa4_idx'),
        ),
    ]
