# Generated by Django 5.2.16 on 2026-07-11 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='setup_status',
            field=models.CharField(blank=True, choices=[('', 'Not started'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('issue', 'Issue')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='status_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status_updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_audi_event_i_402944_idx')],
            },
        ),
    ]
