# Generated by Django 5.2.16 on 2026-07-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_room_setup_status_room_status_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('time_changed', 'Time changed'), ('room_changed', 'Room changed'), ('cancelled', 'Cancelled'), ('uncancelled', 'Un-cancelled'), ('av_changed', 'AV changed')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('room_label', models.CharField(blank=True, max_length=260)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to='events.event')),
            ],
            options={
                'ordering': ['-synced_at', 'starts_at'],
                'indexes': [models.Index(fields=['event', '-synced_at'], name='events_sche_event_i_82eb36_idx')],
            },
        ),
    ]
