# Generated by Django 5.2.16 on 2026-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ical_token',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_name',
            field=models.CharField(blank=True, help_text='Name exactly as it appears in the Staff Shifts sheet — links shifts to this account.', max_length=200),
        ),
    ]
