# Generated by Django 5.2.16 on 2026-07-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ical_token_user_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('midnight', 'Midnight'), ('sakura', 'Sakura')], default='dark', max_length=20),
        ),
    ]
