# Generated by Django 5.2.16 on 2026-07-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_login_enabled', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, max_length=200)),
                ('google_client_secret', models.CharField(blank=True, max_length=200)),
                ('code_login_enabled', models.BooleanField(default=True, help_text='Emailed one-time sign-in codes (requires SMTP below).')),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, max_length=200)),
                ('email_host_password', models.CharField(blank=True, max_length=200)),
                ('default_from_email', models.CharField(blank=True, max_length=200)),
                ('backup_enabled', models.BooleanField(default=True)),
                ('backup_interval_hours', models.PositiveIntegerField(default=24)),
                ('backup_keep', models.PositiveIntegerField(default=14)),
            ],
            options={
                'verbose_name': 'site configuration',
            },
        ),
    ]
