# Generated by Django 5.2.16 on 2026-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('key_authorization', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='acme_contact_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='acme_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='acme_last_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='acme_method',
            field=models.CharField(choices=[('dns01', 'DNS-01 via Cloudflare API (no inbound ports needed)'), ('http01', 'HTTP-01 (internet must reach port 80 -> this app)')], default='dns01', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='acme_staging',
            field=models.BooleanField(default=True, help_text="Use Let's Encrypt's staging environment (untrusted test certs, no rate limits). Turn off once issuance works."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cert_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cloudflare_api_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ssl_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Obtain and auto-renew a certificate, and serve HTTPS on port 8443.'),
        ),
    ]
